[package]
name = "imgcli"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
imgapi = { path = "../imgapi" }
structopt = "0.3.21"
